version: '3.5'
services:

    db:
      container_name: 'djano_startup_mysql'
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: django_startup
      command: --init-file /data/application/init.sql
      volumes:
        - ./deploy/init_server/:/data/application/
      ports:
        - "3306:3306"
        # (HOST:CONTAINER)
      networks:
        vpcbr:
          ipv4_address: 192.168.1.5

    redis-server:
      container_name: 'djano_startup_redis'
      image: redis
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      command: redis-server
      ports:
        - "6379:6379"
        # (HOST:CONTAINER)
      networks:
        vpcbr:
          ipv4_address: 192.168.1.7

    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      restart: always
      volumes:
        - .:/django_http
      ports:
        - "8000:8000"
        # (HOST:CONTAINER)
      depends_on:
        - db
      networks:
        vpcbr:
          ipv4_address: 192.168.1.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
